# Generated by Django 2.2.26 on 2022-02-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
